from tkinter import *
from model import cochesBD
from tkinter import messagebox
from controller import controlador  

class Vistas:
    def __init__(self,ventana):
        ventana.title("Gestion de coches")
        ventana.geometry("700x700")
        ventana.resizable(False,False) #para que la pantalla este fija
        self.interfaz(ventana)

    def interfaz(self, ventana):
        self.borrarPantalla(ventana)
        txt_mp=Label(ventana,text="Menu Principal")
        txt_mp.pack(pady=7)
        btn_auto=Button(ventana,text="Autos",command=lambda: self.menu_autos(ventana))  
        btn_auto.pack(pady=7)
        btn_camioneta=Button(ventana,text="Camionetas", command=lambda: self.menu_camionetas(ventana))
        btn_camioneta.pack(pady=7)
        btn_camiones=Button(ventana,text="Camiones", command=lambda: self.menu_camiones(ventana))
        btn_camiones.pack(pady=7)
        btn_salir=Button(ventana,text="Salir",command=ventana.quit)
        btn_salir.pack(pady=7)

    def borrarPantalla(self,ventana):
        for widget in ventana.winfo_children():
            widget.destroy()

    def menu_autos(self,ventana):
        self.borrarPantalla(ventana)
        txt_autos=Label(ventana,text="Menu Autos")
        txt_autos.pack(pady=7)
        btn_inautos=Button(ventana,text="Insertar",command=lambda: self.insertar_autos(ventana))
        btn_inautos.pack(pady=7)
        btn_conautos=Button(ventana,text="Consultar", command=lambda: self.consultar_autos(ventana))
        btn_conautos.pack(pady=7)
        btn_camautos=Button(ventana,text="Cambiar", command=lambda: self.modificar_autos(ventana))
        btn_camautos.pack(pady=7)
        btn_eliautos=Button(ventana,text="Eliminar", command=lambda: self.eliminar_autos(ventana))
        btn_eliautos.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar", command=lambda: self.interfaz(ventana))
        btn_regresar.pack(pady=7)

    def insertar_autos (self,ventana):
        self.borrarPantalla(ventana)
        txt_tit=Label(ventana,text="Insertar Autos")
        txt_tit.pack(pady=7)
        txt_marca=Label(ventana,text="Ingresa la marca")
        txt_marca.pack(pady=7)
        en_marca=Entry(ventana)
        en_marca.pack(pady=7)
        txt_color=Label(ventana,text="Ingresa el color")
        txt_color.pack(pady=7)
        en_color=Entry(ventana)
        en_color.pack(pady=7)
        txt_modelo=Label(ventana,text="Ingresa el modelo")
        txt_modelo.pack(pady=7)
        en_modelo=Entry(ventana)
        en_modelo.pack(pady=7)
        txt_velocidad=Label(ventana,text="Ingresa la velocidad")
        txt_velocidad.pack(pady=7)
        en_velocidad=Entry(ventana)
        en_velocidad.pack(pady=7)
        txt_caballaje=Label(ventana,text="Ingresa el caballaje")
        txt_caballaje.pack(pady=7)
        en_caballaje=Entry(ventana)
        en_caballaje.pack(pady=7)
        txt_plazas=Label(ventana,text="Ingresa las plazas")
        txt_plazas.pack(pady=7)
        en_plazas=Entry(ventana)
        en_plazas.pack(pady=7)
        btn_guardar=Button(ventana,text="Guardar",command=lambda: "")
        btn_guardar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def consultar_autos(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Consultar Autos")
        txt_titulo.pack(pady=7)
        txt_consultar=Label(ventana,text="Ingresa el ID del auto a buscar")
        txt_consultar.pack(pady=7)
        en_consultar=Entry(ventana)
        en_consultar.pack(pady=7)
        btn_consultar=Button(ventana,text="Consultar",command=lambda: "")
        btn_consultar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def modificar_autos(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Modificar Autos")
        txt_titulo.pack(pady=7)
        txt_modificar=Label(ventana,text="Ingresa el ID del auto a modificar")
        txt_modificar.pack(pady=7)
        en_modificar=Entry(ventana)
        en_modificar.pack(pady=7)
        btn_modificar=Button(ventana,text="Modificar",command=lambda: "")
        btn_modificar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def eliminar_autos(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Eliminar Autos")
        txt_titulo.pack(pady=7)
        txt_eliminar=Label(ventana,text="Ingresa el ID del auto a eliminar")
        txt_eliminar.pack(pady=7)
        en_eliminar=Entry(ventana)
        en_eliminar.pack(pady=7)
        btn_eliminar=Button(ventana,text="Eliminar",command=lambda: "")
        btn_eliminar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)


    def menu_camionetas(self,ventana):
        self.borrarPantalla(ventana)
        txt_camionetas=Label(ventana,text="Menu Camionetas")
        txt_camionetas.pack(pady=7)
        btn_incamionetas=Button(ventana,text="Insertar",command=lambda: self.insertar_camionetas(ventana))
        btn_incamionetas.pack(pady=7)
        btn_concamionetas=Button(ventana,text="Consultar", command=lambda: self.consultar_camionetas(ventana))
        btn_concamionetas.pack(pady=7)
        btn_camcamionetas=Button(ventana,text="Cambiar", command=lambda: self.modificar_camionetas(ventana))
        btn_camcamionetas.pack(pady=7)
        btn_elicamionetas=Button(ventana,text="Eliminar", command=lambda: self.eliminar_camionetas(ventana))
        btn_elicamionetas.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar", command=lambda: self.interfaz(ventana))
        btn_regresar.pack(pady=7)

    def insertar_camionetas(self,ventana):
        self.borrarPantalla(ventana)
        txt_tit=Label(ventana,text="Insertar Camionetas")
        txt_tit.pack(pady=7)
        txt_marca=Label(ventana,text="Ingresa la marca")
        txt_marca.pack(pady=7)
        en_marca=Entry(ventana)
        en_marca.pack(pady=7)
        txt_color=Label(ventana,text="Ingresa el color")
        txt_color.pack(pady=7)
        en_color=Entry(ventana)
        en_color.pack(pady=7)
        txt_modelo=Label(ventana,text="Ingresa el modelo")
        txt_modelo.pack(pady=7)
        en_modelo=Entry(ventana)
        en_modelo.pack(pady=7)
        txt_velocidad=Label(ventana,text="Ingresa la velocidad")
        txt_velocidad.pack(pady=7)
        en_velocidad=Entry(ventana)
        en_velocidad.pack(pady=7)
        txt_caballaje=Label(ventana,text="Ingresa el caballaje")
        txt_caballaje.pack(pady=7)
        en_caballaje=Entry(ventana)
        en_caballaje.pack(pady=7)
        txt_plazas=Label(ventana,text="Ingresa las plazas")
        txt_plazas.pack(pady=7)
        en_plazas=Entry(ventana)
        en_plazas.pack(pady=7)
        txt_plazas=Label(ventana,text="Ingresa la traccion")
        txt_plazas.pack(pady=7)
        en_traccion=Entry(ventana)
        en_traccion.pack(pady=7)
        txt_cerrada=Label(ventana,text="Ingresa cerrada")
        txt_cerrada.pack(pady=7)
        en_plazas=Entry(ventana)
        en_plazas.pack(pady=7)
        btn_guardar=Button(ventana,text="Guardar",command=lambda: "")
        btn_guardar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def consultar_camionetas(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Consultar Camionetas")
        txt_titulo.pack(pady=7)
        txt_consultar=Label(ventana,text="Ingresa el ID de la camioneta a buscar")
        txt_consultar.pack(pady=7)
        en_consultar=Entry(ventana)
        en_consultar.pack(pady=7)
        btn_consultar=Button(ventana,text="Consultar",command=lambda: "")
        btn_consultar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def modificar_camionetas(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Modificar Camionetas")
        txt_titulo.pack(pady=7)
        txt_modificar=Label(ventana,text="Ingresa el ID de la camioneta a modificar")
        txt_modificar.pack(pady=7)
        en_modificar=Entry(ventana)
        en_modificar.pack(pady=7)
        btn_modificar=Button(ventana,text="Modificar",command=lambda: "")
        btn_modificar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def eliminar_camionetas(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Eliminar Camionetas")
        txt_titulo.pack(pady=7)
        txt_eliminar=Label(ventana,text="Ingresa el ID de la camioneta a eliminar")
        txt_eliminar.pack(pady=7)
        en_eliminar=Entry(ventana)
        en_eliminar.pack(pady=7)
        btn_eliminar=Button(ventana,text="Eliminar",command=lambda: "")
        btn_eliminar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)


    def menu_camiones(self,ventana):
        self.borrarPantalla(ventana)
        txt_camiones=Label(ventana,text="Menu Camiones")
        txt_camiones.pack(pady=7)
        btn_incamiones=Button(ventana,text="Insertar", command=lambda: self.insertar_camiones(ventana))
        btn_incamiones.pack(pady=7)
        btn_concamiones=Button(ventana,text="Consultar", command=lambda: self.consultar_camiones(ventana))
        btn_concamiones.pack(pady=7)
        btn_camcamiones=Button(ventana,text="Cambiar", command=lambda: self.modificar_camiones(ventana))
        btn_camcamiones.pack(pady=7)
        btn_elicamiones=Button(ventana,text="Eliminar", command=lambda: self.eliminar_camiones(ventana))
        btn_elicamiones.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar", command=lambda: self.interfaz(ventana))
        btn_regresar.pack(pady=7)

    def insertar_camiones(self,ventana):
        self.borrarPantalla(ventana)
        txt_tit=Label(ventana,text="Insertar Camiones")
        txt_tit.pack(pady=7)
        txt_marca=Label(ventana,text="Ingresa la marca")
        txt_marca.pack(pady=7)
        en_marca=Entry(ventana)
        en_marca.pack(pady=7)
        txt_color=Label(ventana,text="Ingresa el color")
        txt_color.pack(pady=7)
        en_color=Entry(ventana)
        en_color.pack(pady=7)
        txt_modelo=Label(ventana,text="Ingresa el modelo")
        txt_modelo.pack(pady=7)
        en_modelo=Entry(ventana)
        en_modelo.pack(pady=7)
        txt_velocidad=Label(ventana,text="Ingresa la velocidad")
        txt_velocidad.pack(pady=7)
        en_velocidad=Entry(ventana)
        en_velocidad.pack(pady=7)
        txt_caballaje=Label(ventana,text="Ingresa el caballaje")
        txt_caballaje.pack(pady=7)
        en_caballaje=Entry(ventana)
        en_caballaje.pack(pady=7)
        txt_plazas=Label(ventana,text="Ingresa las plazas")
        txt_plazas.pack(pady=7)
        en_plazas=Entry(ventana)
        en_plazas.pack(pady=7)
        txt_eje=Label(ventana,text="Ingresa el eje")
        txt_eje.pack(pady=7)
        en_eje=Entry(ventana)
        en_eje.pack(pady=7)
        txt_capacidad=Label(ventana,text="Ingresa la capacidad de carga")
        txt_capacidad.pack(pady=7)
        en_capacidad=Entry(ventana)
        en_capacidad.pack(pady=7)
        btn_guardar=Button(ventana,text="Guardar",command=lambda: "")
        btn_guardar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def consultar_camiones(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Consultar Camiones")
        txt_titulo.pack(pady=7)
        txt_consultar=Label(ventana,text="Ingresa el ID del camion a buscar")
        txt_consultar.pack(pady=7)
        en_consultar=Entry(ventana)
        en_consultar.pack(pady=7)
        btn_consultar=Button(ventana,text="Consultar",command=lambda: "")
        btn_consultar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def modificar_camiones(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Modificar Camiones")
        txt_titulo.pack(pady=7)
        txt_modificar=Label(ventana,text="Ingresa el ID del camion a modificar")
        txt_modificar.pack(pady=7)
        en_modificar=Entry(ventana)
        en_modificar.pack(pady=7)
        btn_modificar=Button(ventana,text="Modificar",command=lambda: "")
        btn_modificar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)

    def eliminar_camiones(self,ventana):
        self.borrarPantalla(ventana)
        txt_titulo=Label(ventana,text="Eliminar Camiones")
        txt_titulo.pack(pady=7)
        txt_eliminar=Label(ventana,text="Ingresa el ID del camion a eliminar")
        txt_eliminar.pack(pady=7)
        en_eliminar=Entry(ventana)
        en_eliminar.pack(pady=7)
        btn_eliminar=Button(ventana,text="Eliminar",command=lambda: "")
        btn_eliminar.pack(pady=7)
        btn_regresar=Button(ventana,text="Regresar",command=lambda: self.menu_autos(ventana))
        btn_regresar.pack(pady=7)